export type PropertyRecord = {
  id: string;
  title: string;
  slug: string;
  description: string;
  location: string;
  sector: string;
  city: string;
  priceInr: number;
  type: string;
  status: string;
  bedrooms: number | null;
  bathrooms: number | null;
  areaSqft: number;
  featured: boolean;
  imageUrls: string;
  amenities: string;
  sourceType: string;
  sourcePlatform: string | null;
  sourceUrl: string | null;
  priceLastVerified: string | null;
  photoRightsStatus: string;
  approvalStatus: string;
  boostTier: string;
  leadRoutingMode: string;
  featuredRequested: boolean;
  listingContactName: string | null;
  listingContactPhone: string | null;
  listingContactRole: string | null;
  vendorId: string | null;
  createdAt: string;
  updatedAt: string;
};

export type LeadRecord = {
  id: string;
  name: string;
  phone: string;
  requirement: string;
  propertyId: string | null;
  routingStatus: string;
  sourceChannel: string;
  createdAt: string;
};
